[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"
java = "21"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:5.1.0"
kotlin-logging = "io.github.oshai:kotlin-logging-jvm:7.0.14"
testcontainers-localstack = "org.testcontainers:testcontainers-localstack:2.0.3"
kotest-assertions-core= "io.kotest:kotest-assertions-core:6.1.0"
awaitility-kotlin = "org.awaitility:awaitility-kotlin:4.3.0"
mockk = "io.mockk:mockk:1.14.7"
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:2.1.20"
kaml = "com.charleskorn.kaml:kaml:0.104.0"
kotlinx-io-core = "org.jetbrains.kotlinx:kotlinx-io-core:0.8.0"
logback-classic="ch.qos.logback:logback-classic:1.5.25"
wiremock-standalone="org.wiremock:wiremock-standalone:3.13.2"
[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version = "0.11.3" }
git-version = { id = "com.palantir.git-version", version = "4.2.0" }
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
stacktracedecoroutinator = { id = "dev.reformator.stacktracedecoroutinator", version = "2.6.1" }